# Generated by Django 5.1 on 2024-11-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0007_auto_20150711_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category3',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extract.article'),
        ),
        migrations.AlterField(
            model_name='category35',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extract.article'),
        ),
        migrations.AlterField(
            model_name='image',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extract.article'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extract.article'),
        ),
        migrations.AlterField(
            model_name='outlink',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extract.article'),
        ),
    ]
